name: Secrets Scan
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  secrets_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Secrets Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: |
          --exclude-paths=.thog-exclude-paths
          --user-agent-suffix=thalex-security-scanner
          --no-verification
          --results=unverified
